//
// Created by jessica on 16/09/19.
//

#ifndef DONCEY_KONG_JR_GLOBALVARIABLES_H
#define DONCEY_KONG_JR_GLOBALVARIABLES_H



#define SCREEN_WIDTH 980
#define SCREEN_HEIGHT 668
#define SPEED 3
#define JUMPSPEED 8
#define GRAVITY 3
#define LEDGEAMOUNT 7
#define ROPEAMOUNT 8
#define MONKEYFRAMES 6
#define BLUECROCOFRAMES 1
#define REDCROCOFRAMES 1
#define LIVESFRAMES 4
#define LIVESAMOUNT 3
#define CROCOSPEED 2

#endif //DONCEY_KONG_JR_GLOBALVARIABLES_H
